cc_test(
    name = "binary_search_test",
    timeout = "short",
    srcs = glob(["**/*.cpp"]),
    copts = ["-std=c++20"],
    deps = [
        "//lib/binary_search",
        "@gtest",
        "@gtest//:gtest_main",
    ],
)
